version: "3.7"
services:
  telegraf:
    image: "telegraf:1.20.3"
    container_name: "telegraf"
    hostname: $HOSTNAME
    restart: always
    environment:
      TZ: Asia/Shanghai
      HOST_MOUNT_PREFIX: /hostfs
      HOST_PROC: /hostfs/proc
    volumes:
      - ./telegrafetc/telegraf.conf:/etc/telegraf/telegraf.conf
      - ./telegrafetc/telegraf.d:/etc/telegraf/telegraf.d
      - /:/hostfs:ro
    ports:
      - "8125:8125/udp"
      - "8092:8092/udp"
      - "8094:8094/tcp"
    command: telegraf --config /etc/telegraf/telegraf.conf --config-directory /etc/telegraf/telegraf.d
